Disallow in-source builds

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -170,6 +170,13 @@ ISTHISWINDOWS=no
 niceheader
 echo ""
 
+# disallow user to run configure in the source directory
+if test "$CDIR" = "$SOURCEDIR"; then
+	echo "[ERROR 99] Please do not run $0 right in the source directory. Create a build directory somewhere and run it from here. For example:"
+	echo "cd \"$SOURCEDIR\" && mkdir builddir && cd builddir && ../configure $*"
+	exit 99
+fi
+
 # remove old debug configure thing
 if test -e "$CDIR/muleconfigure.log"; then
 	rm -r -f "$CDIR/muleconfigure.log"
